apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: avalier-demo7
  #namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: avalier-demo7
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70


 