apiVersion: v1
kind: Service
metadata:
  name: {{ include "avalier-demo7.fullname" . }}
  labels:
    app: {{ include "avalier-demo7.fullname" . }}
    {{- include "avalier-demo7.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    {{- include "avalier-demo7.selectorLabels" . | nindent 4 }}
